version: "4.0"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf

  service1:
    container_name: service1
    image: service1:latest
    build: ./service1

  service2:
    container_name: service2
    image: service2:latest
    build: ./service2

  service3:
    container_name: service3
    image: service3:latest
    build: ./service3

  service4:
    container_name: service4
    image: service4:latest
    build: ./service4

