version: "4.0"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf

  flask-app:
    container_name: service1
    image: service1:latest
    build: ./service1

