- hosts: all
  tasks:
  - name: "Ping {{ inventory_hostname }}"
    ping:
    register: ping_info

  - name: "Show ping_info in console"
    debug:
      msg: "{{ ping_info }}"

- hosts: swarm
  tasks:
  - name: "Install Docker {{ inventory_hostname }}"
    apt: 
      name: docker
      state: latest
      update_cache: true

- hosts: server
  tasks: 
  - name: "Install Nginx on {{ inventory_hostname }}"
    apt:
      name: nginx
      state: latest
      update_cahce: true
  - name: "Start Nginx on {{ inventory_hostname }}"
    service:
      name: nginx
      state: started