# tasks for docker swarm nodes


- name: "Install Docker {{ inventory_hostname }}"
  shell:
    cmd: curl https://get.docker.com | bash

- name: "Assign Jenkins to Docker group {{ inventory_hostname }}"
  become: true
  user:
    name: jenkins
    groups: docker
    append: yes