#deploy nginx

- name: "Install Nginx on Nginx server"
  apt:
    name: nginx
    state: latest
    update_cache: true

- name: "Config nginx"
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    
- name: "Start Nginx on server"
  service:
    name: nginx
    state: started
  
- name: "Restart Nginx on server"
  service:
    name: nginx
    state: restarted