- hosts: all
  tasks:
  - name: "Ping {{ inventory_hostname }}"
    ping:
    register: ping_info

  - name: "Show ping_info in console"
    debug:
      msg: "{{ ping_info }}"

- hosts: swarm
  roles:
  - docker

- hosts: manager
  roles:
  - manager

- hosts: worker
  roles:
  - swarm

- hosts: server
  roles:
  - nginx 
