# tasks for docker swarm nodes


- name: "Add worker {{ inventory_hostname }} to swarm}}
  docker_swarm:
    state: join
    advertise_addr: node2
    join_token: "{{ hostvars['node1']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'node1:2377']