# tasks for docker swarm nodes

- name: "Initialise the Swarm"
  docker_swarm:
    state: present

- name: "Add worker {{ inventory_hostname }} to swarm}}
  docker_swarm:
    state: join
    advertise_addr: node2
    join_token: SWMTKN-1-03k5ce69t900gqgu5btfry38ao7pqj58l65e51ffr5wi5a9zkj-esak60aoy1bfksbdiesqk9lwp
    remote_addrs: [ 'node1:2377']




