# tasks for docker swarm nodes

- name: "Initialise the Swarm"
  docker_swarm:
    state: present

- name: "Add worker {{ inventory_hostname }} to swarm}}
  docker_swarm:
    state: join
    advertise_addr: node2
    join_token: "{{ hostvars ['node1']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'node1:2377']

- name: join node to the cluster
    shell: docker swarm join --token {{ hostvars[item]['docker_worker_token'] }} {{ managerip }}:2377
    with_items:
      - "{{ groups['manager'] }}"