# tasks for docker swarm nodes

- name: "Initialise the Swarm"
  docker_swarm:
    state: present

- name: "Add worker {{ inventory_hostname }} to swarm}}
  command: docker swarm join --token SWMTKN-1-03k5ce69t900gqgu5btfry38ao7pqj58l65e51ffr5wi5a9zkj-esak60aoy1bfksbdiesqk9lwp 10.154.0.21:2377
