#initialise the swarm manager and pull images

- name: "Initialise the Swarm"
  docker_swarm:
    state: present

- name: "Get Swarm Info"
  docker_swarm_info:
  register: swarm_info


- name: "Madam Jira on manager"
  docker_stack:
    state: present
    name: madam-jira
    compose:
      - /home/jenkins/docker-compose.yaml