#initialise the swarm manager and pull images

- name: "Initialise the Swarm"
  docker_swarm:
    state: present

- name: "Get Swarm Info"
  shell: docker swarm join-token worker
  register: swarm_info


- name: "Madam Jira on {{ inventory_hostname }} manager"
  docker_stack:
    state: present
    name: madam-jira
    compose:
      - /home/jenkins/docker-compose.yaml